### ISSUE TITLE
Criação do zenhub

### ISSUE THREAD

**Issue by mibasFerraz** [fga-eps-mds/MDS-2020-2-G3#19]
### Descrição:
Realizar uma conta e aprender a utilizar o ZenHub.

### Objetivos:

- [x] Todos os membros do grupo tenham criado uma conta.

**Comment by mibasFerraz** [comment]
Conta e workspace criados

**Comment by lbvx** [comment]
Pelo o que entendi, o ZenHub ajuda na visualização do progresso de desenvolvimento do projeto. É possível associar cada issue a um nível de progresso, como backlog de produto, backlog da sprint, em desenvolvimento, etc. Por lá também é possível criar roadmap do projeto.

**Comment by GRVial** [comment]
Zenhub instalado na máquina.

**Comment by vnsrz** [comment]
Zenhub instalado na máquina.
