### ISSUE TITLE
Aprender a usar o github

### ISSUE THREAD

**Issue by mibasFerraz** [fga-eps-mds/MDS-2020-2-G3#2]
Ver a aula síncrona da sprint 0 ou a assícrona no canal do youtube de mds

**Comment by mibasFerraz** [comment]
Aprendizado básico sobre Github (Push, Pull, Commit, Status, Add, Init, Config, Clone, Branch, Log).

**Comment by vnsrz** [comment]
Comandos no git:

commit

$ fork
$ git clone [link]
$ git checkout -b [branch name]
$ git add [stuff]
$ git commit -m "message"
$ git push

sync fork

$ git remote add upstream [original rep]
$ git remote -v

$ git fetch upstream
$ git checkout [default branch]
$ git merge upstream/[default branch]

**Comment by GRVial** [comment]
Markdown sheet [Link](https://www.markdownguide.org/cheat-sheet/)

**Comment by lbvx** [comment]
Cheat sheet de git: https://education.github.com/git-cheat-sheet-education.pdf
