### ISSUE TITLE
Definir tecnologias 

### ISSUE THREAD

**Issue by GRVial** [fga-eps-mds/MDS-2020-2-G3#3]
### Descrição:

Definir as tecnologias que serão utilizadas no projeto.

### Objetivos:

- [x] Pesquisar tecnologias a serem usadas no projeto

### Critérios de aceitação:

- [x] Ter tecnologias definidas para o projeto

**Comment by lbvx** [comment]
[Discord.py](https://discordpy.readthedocs.io/en/latest/)

**Comment by mibasFerraz** [comment]
Api do instagram
