### ISSUE TITLE
Padronização do formato de Issues e Pull Requests

### ISSUE THREAD

**Issue by lbvx** [fga-eps-mds/MDS-2020-2-G3#8]
## Descrição:
Criação de padrões para criação e postagem de Issues e Pull Requests.

## Tarefas: 

- [x] Criar template de issues
- [x] Criar template de pull requests

#### Critério de aceitação: 

- [x] Criar templates
- [x] Todos contribuidores devem seguir o formato das templates

**Comment by vnsrz** [comment]
Templates para pull request e issues adicionados.
